# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = ${UNREAL_PATH}
GAMEPROJECTFILE =${PWD}/SimpleShooter.uproject

TARGETS = \
	DotNetPerforceLib-Linux-DebugGame  \
	DotNetPerforceLib-Linux-Shipping  \
	DotNetPerforceLib \
	EventLoopUnitTests-Linux-DebugGame  \
	EventLoopUnitTests-Linux-Shipping  \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	SimpleShooter-Linux-DebugGame  \
	SimpleShooter-Linux-Shipping  \
	SimpleShooter \
	SimpleShooterEditor-Linux-DebugGame  \
	SimpleShooterEditor-Linux-Shipping  \
	SimpleShooterEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SimpleShooterEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SimpleShooterEditor-Linux-Debug


DotNetPerforceLib-Linux-DebugGame:
	 $(BUILD) DotNetPerforceLib Linux DebugGame  $(ARGS)

DotNetPerforceLib-Linux-Shipping:
	 $(BUILD) DotNetPerforceLib Linux Shipping  $(ARGS)

DotNetPerforceLib:
	 $(BUILD) DotNetPerforceLib Linux Development  $(ARGS)

EventLoopUnitTests-Linux-DebugGame:
	 $(BUILD) EventLoopUnitTests Linux DebugGame  $(ARGS)

EventLoopUnitTests-Linux-Shipping:
	 $(BUILD) EventLoopUnitTests Linux Shipping  $(ARGS)

EventLoopUnitTests:
	 $(BUILD) EventLoopUnitTests Linux Development  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

SimpleShooter-Linux-DebugGame:
	 $(PROJECTBUILD) SimpleShooter Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SimpleShooter-Linux-Shipping:
	 $(PROJECTBUILD) SimpleShooter Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SimpleShooter:
	 $(PROJECTBUILD) SimpleShooter Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SimpleShooterEditor-Linux-DebugGame:
	 $(PROJECTBUILD) SimpleShooterEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SimpleShooterEditor-Linux-Shipping:
	 $(PROJECTBUILD) SimpleShooterEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SimpleShooterEditor:
	 $(PROJECTBUILD) SimpleShooterEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
